# Generated by Django 3.1.4 on 2020-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_activities_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='name',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
