# Generated by Django 3.1.4 on 2020-12-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0003_auto_20201221_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='number_admin',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
